#!/bin/sh


set -e

#DEBHELPER#

case "$1" in
    configure)

    mkdir -p /var/run/mastermind-minion

    /usr/local/bin/mastermind-minion/update_db.sh

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
